name: Publish on releases

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Publish plugin to Gradle Portal
        uses: burrunan/gradle-cache-action@v1
        with:
          # jobs with different JDK versions can't share caches
          job-id: jdk11
          arguments: publishPlugins
          properties: |
            version=${{ github.event.release.tag_name }}
            gradle.publish.key=${{ secrets.GRADLE_API_KEY }}
            gradle.publish.secret=${{ secrets.GRADLE_API_SECRET }}
